### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by BeckyLanger** [gilphilbert/jblabels#1]
Good Morning!
I love your juke.studio!  This is perfect for me as I have a TON of records for my jukebox, but I do not have most of the labels.  However, when I print the labels from your program, there is NO spacing between the labels which makes it difficult to cut them and still have a bottom border.  Is there anyway you can add a small space between each label?
[red labels 1.pdf](https://github.com/gilphilbert/jukestudio/files/6117315/red.labels.1.pdf)

**Comment by gilphilbert** [comment]
Glad it's useful for you!

The labels are designed to print with no spaces - this is largely because the pre-printed perforated labels use this exact format. I use a steel ruler and a sharp knife to cut up the labels (I print on medium weight card).

If that doesn't work for you, I can add an option to separate the labels slightly so you can cut them out individually

**Comment by BeckyLanger** [comment]
I'd really appreciate it if you could add the spacing, I gave it a shot cutting them with a razor, but I'm not the best at it.  I tried using a paper cutter and the blade is a little too thick for the labels.

**Comment by gilphilbert** [comment]
Well, good news and bad news... the good news is that the fix is now on the site! Head to the "Design" tab at the top and in the window, select "Wider spacing".

The bad news is that my hoster messed up and now the site is down. I switched providers, it'll take a little while before it's back again.

The following link should work in the meantime:
https://gilphilbert.github.io/jukestudio/

Test it out and let me know if it works for you.

**Comment by BeckyLanger** [comment]
Thank you so much for doing all that work, I really appreciate it!

**Comment by gilphilbert** [comment]
No problem! The site's backup and the link above will forward to it now. I'll close this issue - if you're having problems still you can reopen it again

**Comment by BeckyLanger** [comment]
Okay thank you

**Comment by TMURRAY517** [comment]
Hello, the Wider Spacing option doesn't seem to work when I go to print.  It doesn't stay checked in the design tab. 
Could you please check when you have time as it would really help with cutting out the labels.  

Thank you!
