### ISSUE TITLE
Delete records , and resize for wall box 

### ISSUE THREAD

**Issue by dmueller674** [gilphilbert/jblabels#4]
Hi there , I add Records to this when I buy them , sometime 50 at a time . I would like to see were  someone can delete Muti  records at a time . 

 I have 3 wall boxes , and its a real pain to try to resize the labels , If all possible , can you add a feature to resize the label width with out looking quality ? 

 Thank you .

David

**Comment by gilphilbert** [comment]
Apologies for the delay. OK, so two different requests.

1) Yes, there's currently no multi-delete. This is something I have been planning for a while and can work on. Would you want to discard everything or just select records?

2) I don't have any wallboxes (or wallbox labels). Do you know the dimensions for the wallbox labels? I can make an option to print wallbox labels instead of full-size ones

**Comment by dmueller674** [comment]
Thanks for getting back to me .

1.  delete :  I would think  a select all and or uncheck the ones you want
before or after the select all . That would be more helpful for many people
.


2.  Wall box  size  :   I personally have 2 wall boxes and different sizes.
1 wall box (Seeburg)  takes the full size and the other is the same
height. @ 1 inch but @  2- 3/8th inch ( 1 X 2.375)  AMI  wall box .


Thank you again , and hope your able to do this for everyone .
Your time , and skill  set is very appreciated .

David Mueller

**Comment by gilphilbert** [comment]
The delete function should be pretty simple to implement, I'm not worried about that one.

The wallbox one will be a little more complicated since many of the calculations on how long text can be, margin sizes, where the images go (Christmas themes) are all based on the label being a fixed width of 3". I can certainly do it, I'll just need a little time to work on that. Out of interest, do you have any original title strips for the wallboxes? I'm interested, do they use smaller fonts?

**Comment by dmueller674** [comment]
Hello , Yes I have some old jukebox labels but they are the same size as
yours . What I did to get mine down to size for the wall box, is adjust
size in preview ( Mac) . all what happens is the text shrinks as it is
pushed together. tall and skinny print .I included a sample of what it
looks likes wall box size

**Comment by gilphilbert** [comment]
Apologies for the extremely long delay... I've rewritten the entire app and now supporting these features is easier.

I've added support for multi-delete (you can select as many as you like and delete them all)

I will add support for smaller labels, I'm tracking that separately as #6
